# Generated by Django 5.2.3 on 2025-06-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('very_sad', 'Very Sad')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mood entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
