# Generated by Django 5.2.3 on 2025-06-16 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motivation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermotivation',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivation.quote'),
        ),
        migrations.AddField(
            model_name='usermotivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
